### ISSUE TITLE
Add support for `workflow_dispatch` event trigger

### ISSUE THREAD

**Issue by garysassano** [DevSecTop/TF-via-PR#238]
#### Describe the bug

Getting this error when triggering the workflow manually from a `workflow_dispatch` event.

#### Screenshots

![image](https://github.com/DevSecTop/TF-via-PR/assets/10464497/3f1f213e-0870-4750-a06d-06c92d4f2c1b)

**Comment by RDhar** [comment]
Shipped in [v11.0.0](https://github.com/DevSecTop/TF-via-PR/releases/tag/v11.0.0) :rocket:
