### ISSUE TITLE
Expose detailed exit code as an output

### ISSUE THREAD

**Issue by chris3ware** [DevSecTop/TF-via-PR#297]
#### Is your feature request related to a problem

It would be useful to be able to check the detailed exit code as a condition for running subsequent jobs

#### Describe the solution you'd like

detailed exit code to be added as an output

**Comment by rdhar** [comment]
I reckon you're right — it'd be useful to have, and surprised it's not come up earlier!

Outta curiosity, do you use either [setup-opentofu](https://github.com/opentofu/setup-opentofu) or [setup-terraform](https://github.com/hashicorp/setup-terraform) in your workflow already? That might make it a tad easier to test the new `exitcode` output.

**Comment by chris3ware** [comment]
Hi, I do, I use the OpenTofu action.

**Comment by rdhar** [comment]
Excellent, then the latest [v11.4.0](https://github.com/DevSecTop/TF-via-PR/releases/tag/v11.4.0) release will support this implementation for both options.

By default, the new `exitcode` [output parameter](https://github.com/DevSecTop/TF-via-PR?tab=readme-ov-file#outputs) will output `0` (succeeded) or `1` (failed).

By passing in `arg_detailed_exitcode: true`, then `exitcode` will return one of the [documented](https://opentofu.org/docs/cli/commands/plan/#other-options) exit codes:
- `0` = Succeeded with empty diff (no changes)
- `1` = Error
- `2` = Succeeded with non-empty diff (changes present)

This has been validated by my [public test run](https://github.com/DevSecTop/TF-via-PR/actions/runs/10835036156/job/30065638494#step:6:31) associated with [this workflow](https://github.com/DevSecTop/TF-via-PR/actions/runs/10835036156/workflow#L52-L60).
