### ISSUE TITLE
Respect workflow default working directory

### ISSUE THREAD

**Issue by chris3ware** [DevSecTop/TF-via-PR#321]
#### Describe the bug

Plan and apply initialise an empty working directory without `arg_chdir`  set despite the default working directory being set.

#### To Reproduce

Set a default working directory in your workflow:

```
defaults:
  run:
    working-directory: ./terraform
```

Run the action without `arg_chdir` set

#### Expected behavior

The action should use the default working directory to initialise terraform

#### Screenshots

<img width="984" alt="Screenshot 2024-10-17 at 05 37 51" src="https://github.com/user-attachments/assets/f3d0637c-b7a8-467b-a508-a48616e50a02">

#### Additional context

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/setting-a-default-shell-and-working-directory

**Comment by rdhar** [comment]
Great request, and something I'd wanted as well to ease to adoption of this action.

However, I don't think it's possible for an action to detect whether the default working directory is set, is it?

**Comment by chris3ware** [comment]
> Great request, and something I'd wanted as well to ease to adoption of this action.
> 
> However, I don't think it's possible for an action to detect whether the default working directory is set, is it?

I've ~re-read~ read the documentation properly, and it clearly states:

> You can use defaults.run to provide default shell and working-directory options for all [run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) steps in a workflow.

The other jobs in my workflow, like tflint, that are working without `-chdir` are `run` steps.

**Comment by rdhar** [comment]
Ah that's a bit of shame, @chris3ware. I would've liked a consistent working directory setting as well.

As a workaround, I guess an env variable could be created and passed into both the default working directory as well as the action's chdir, so at least it's defined once and consistent everywhere?

**Comment by chris3ware** [comment]
> I still agree that `arg-chdir` is less than intuitive in terms of providing the path to where TF should be run.
> 
> While it doesn't address the specific need identified by this issue, I wonder if a new `working-directory` input parameter (which is aliased to `arg-chdir`) would go some way towards abating confusion. Given a new major release is expected to ship within the next week, this'd be an easy one to slip in.

Yes, that option could be useful. `working-directory` is quite a common input for actions.

**Comment by rdhar** [comment]
Nice one, added to the last-minute backlog. Confident it'll be shipped within the new week.
