### ISSUE TITLE
Skip upload of plan when there is no changes

### ISSUE THREAD

**Issue by silnels-greenlane** [DevSecTop/TF-via-PR#361]
#### Is your feature request related to a problem

Skip the upload of the plan file if there is no changes.

#### Describe the solution you'd like

Not running unnecessary steps, like **init** or **plan** when there is nothing to do.

#### Additional context

When you have a workflow that does **plan** and **apply**, its possible to look at the **exitcode** before running **apply**.
I've a different approach, where the **plan** is generated thru a pull request and applied when merged to the main branch.
If the plan is not uploaded, i can somehow check if the file exist before trying to applying.

This approach would save setting up agents and running steps that are not needed.

**Comment by rdhar** [comment]
Good shout, @silnels-greenlane.

In cases where the plan command exits with code 0 (no diff), we want apply to be skipped altogether. Much like how Atlantis does it, IIRC.

Can you clarify if your plan and apply commands are occurring within the same workflow (not necessarily the same job)?

Ie., when you go to apply, do you also run a plan as a pre-step/job?

**Comment by fulgas** [comment]
@rdhar I've both scenarios, but the plan workflow is that the **plan** is build during a Pull Request and **applied** after the merged to main.

So if a Pull Request when it builds the **plan** and the exit code is **0**, I don't need the upload of the state file. 

And with that I also check if the **apply** is needed after the merge.

On the other scenario, I have allowed to run **plan** and **apply** on main when the above approach causes problems on the plan.

**Comment by rdhar** [comment]
I'm on the same page with you as far as a no-diff plan being called out as such for subsequent workflow decisions. This is addressed by the [exitcode](https://github.com/DevSecTop/TF-via-PR?tab=readme-ov-file#outputs) output, spanning: 0 (success with no diff), 1 (error), and 2 (success with diff), per [documentation](https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode). 

I'm apprehensive to not upload a no-diff plan file, however. A plan file is a specific state proposal with corresponding revision number. Even no-diff is itself a proposal. 

Take for example a scenario:
- PR alpha is planned with no diff
- PR bravo is planned with a diff
- PR bravo is merged and applied successfully
- PR alpha's plan is stale now
- PR alpha is merged and apply skipped, thereby state may or may not reflect IaC.

If PR branches are regularly updated, this shouldn't be an issue. Though, there may be an edge-case where there might no infra changes, but there may be some changes to existing outputs instead.

**Comment by fulgas** [comment]
On my current setup I don't allow merge on branch main if the Pull Request branch is outdated. So i'm not reaching the point where the plan might be stale.

**Comment by rdhar** [comment]
Obviously not going to close a perfectly valid issue/request! But, admittedly, this has resulted in severe head-scratching with regards to resolution.

While the request is to skip plan-file upload if there's no diff, the actual desire here is to skip apply if there's no diff. Checking for the presence of the plan-file is one way towards meeting that goal.

Which leads to our first blocker: how would we go about checking if the relevant plan-file artifact exists, given their unique deterministic naming convention, and given a failed `plan` won't store a plan-file either?

---
Let's revisit your workaround of doing an extra `plan` to check its [exitcode](https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode) before deciding to `apply` on merge. This entails authentication, followed by `init` then `plan`. Potentially lengthy and likely slow process.

What if, instead, we could just use the unique deterministic name to download the plan-file and parse it directly to check for diff? That'd save time over `init`+`plan` and could then be used to decide whether a subsequent `apply` job is necessary to run.

All that'd require is:
- TF-via-PR to support a new command which doesn't `init`, `plan` or `apply`—only outputs the unique identifier name.
- You to download the plan-file artifact with the identifier, then `grep` it for a line starting with "Plan:" to check for diff.

---
Straightforward in theory, but needs a working example and a little finesse (i.e., decrypting plan file before it can be parsed). Will keep this thread updated on progress.

**Comment by rdhar** [comment]
To better demonstrate the above approach, a new workflow example has been added with [conditional job stages based on the plan file content](https://github.com/DevSecTop/TF-via-PR/blob/main/.github/examples/pr_push_stages.yaml).

Your contribution has been credited in [v12.1.0](https://github.com/DevSecTop/TF-via-PR/releases/tag/v12.1.0) release, thank you!

**Comment by rdhar** [comment]
Been a month onwards and I was keen to follow up on where you landed with the conditional exit codes and if the above workflow example met your use-case, @fulgas?
